server:
  port: 9002
spring: 
  application:
    name: jtm-query-service
eureka: 
  server:
    name: javatv
    password: china2018no1
  client: 
    service-url: 
      defaultZone: http://${eureka.server.username}:${eureka.server.password}@localhost:9000/eureka/